name = "Cobblemonclizzy"
author = "momo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db3d85b805a1f28dfc452d3c6cd21086cc8b868d8c7a3b502fb5107c24e7fa3c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
