name = "Cobblemonclizzy"
author = "momo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7379579e366f76659b25849b2b818cfb29416dc2c562107cf92b187136e8af77"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
