		[types.crystal_type.pastel]
			#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
			topaz = true
			citrine = true
			onyx = true
			moonstone = true
			bismuth = true
			azurite = true
			malachite = true
			bloodstone = true

		[types.crystal_type.galosphere]
			allurite = true
			lumiere = true

		[types.metal_type.darkerdepths]
			forsaken_bronze = true

		[types.metal_type.galosphere]
			palladium = true

		[types.metal_type.caverns_and_chasms]
			silver = true
			tin = true
			necromium = true

		[types.metal_type.enderscape]
			shadoline = true

		[types.metal_type.create]
			zinc = true
			brass = true

		[types.metal_type.embers]
			lead = true
			silver = true
			dawnstone = true
			mithril = true

		[types.gem_type.cobblemon]
			fire_stone = true
			ice_stone = true

		[types.gem_type.caverns_and_chasms]
			spinel = true
			turquoise = true

		[types.gem_type.mega_showdown]
			keystone = true

		[types.gem_type.enderscape]
			nebulite = true

		[types.stone_type.galosphere]
			pink_salt = true
			rose_pink_salt = true
			pastel_pink_salt = true

		[types.stone_type.atmospheric]
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.supplementaries]
			brittlestone = true

		[types.stone_type.darkerdepths]
			aridrock = true
			duskrock = true
			darkslate = true
			grimestone = true

		[types.stone_type.pastel]
			blackslag = true
			preservation_stone = true

		[types.stone_type.naturalist]
			shellstone = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true
			cylindrite = true
			cassiterite = true
			rhyolite = true

		[types.stone_type.enderscape]
			mirestone = true
			veradite = true
			kurodite = true

		[types.stone_type.nomansland]
			silt = true
			siltstone = true

		[types.cake.dungeonsdelight]
			monster_cake = true

		[types.cake.farmersrespite]
			coffee_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.lantern.netherexp]
			ancient_lantern = true

		[types.lantern.darkerdepths]
			glowshroom_lantern = true

		[types.lantern.dungeonsdelight]
			living_lantern = true

		[types.lantern.caverns_and_chasms]
			cupric_lantern = true
			copper_lantern = true
			exposed_copper_lantern = true
			weathered_copper_lantern = true
			oxidized_copper_lantern = true
			waxed_copper_lantern = true
			waxed_exposed_copper_lantern = true
			waxed_weathered_copper_lantern = true
			waxed_oxidized_copper_lantern = true

		[types.lantern.enderscape]
			bulb_lantern = true

		[types.wood_type.abundant_atmosphere]
			red_bamboo = true
			ashroot = true
			gourdrot = true

		[types.wood_type.dungeonsdelight]
			wormwood = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.netherexp]
			claret = true

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.wood_type.pastel]
			black = true
			blue = true
			brown = true
			cyan = true
			gray = true
			green = true
			light_blue = true
			light_gray = true
			lime = true
			magenta = true
			orange = true
			pink = true
			purple = true
			red = true
			white = true
			yellow = true
			weeping_gala = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.enderscape]
			veiled = true
			celestial = true
			murublight = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.spawn]
			rotten = true
			date = true

		[types.wood_type.malum]
			runewood = true
			soulwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.cobblemon]
			apricorn = true
			saccharine = true

		[types.leaves_type.pastel]
			weeping_gala = true
			nephrite_blossom = true
			spirit_sallow = true
			black = true
			blue = true
			brown = true
			cyan = true
			gray = true
			green = true
			light_blue = true
			light_gray = true
			lime = true
			magenta = true
			orange = true
			pink = true
			purple = true
			red = true
			white = true
			yellow = true

		[types.leaves_type.abundant_atmosphere]
			ashroot = true
			gourdrot = true

		[types.leaves_type.galosphere]
			opal = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.nomansland]
			yellow_birch = true
			autumnal_oak = true
			pale_cherry = true
			frosted = true
			pine = true
			maple = true
			red_maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.spawn]
			date = true

		[types.leaves_type.malum]
			runewood = true
			azure_runewood = true
			soulwood = true

		[entries.metal_type.minecraft]
			nugget = true

		[entries.metal_type.create]
			table_cloth = true
			tile_slab = true
			door = true
			ornate_window = true
			ladder = true
			sheet = true
			ornate_window_pane = true
			scaffolding = true
			shingle_slab = true
			shingle_stairs = true
			tiles = true
			shingles = true
			tile_stairs = true
			casing = true

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			polished_cut_stairs = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.quark]
			polished_vertical_slab = true
			pillar = true
			vertical_slab = true

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

		[entries.wood_type.nomansland]
			bookshelf = true
			trimmed_planks = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.another_furniture]
			flower_box = true
			shelf = true
			shutter = true
			bench = true
			table = true
			drawer = true
			chair = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			hollow_log = true
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			vertical_slab = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true
